/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/indexadmin': RouteRecordInfo<'/admin/indexadmin', '/admin/indexadmin', Record<never, never>, Record<never, never>>,
    '/admin/loginadmin': RouteRecordInfo<'/admin/loginadmin', '/admin/loginadmin', Record<never, never>, Record<never, never>>,
    '/Centre/estatassignacions': RouteRecordInfo<'/Centre/estatassignacions', '/Centre/estatassignacions', Record<never, never>, Record<never, never>>,
    '/Centre/estatpeticionsscreen': RouteRecordInfo<'/Centre/estatpeticionsscreen', '/Centre/estatpeticionsscreen', Record<never, never>, Record<never, never>>,
    '/Centre/formularialumnes': RouteRecordInfo<'/Centre/formularialumnes', '/Centre/formularialumnes', Record<never, never>, Record<never, never>>,
    '/Centre/iniciCentreScreen': RouteRecordInfo<'/Centre/iniciCentreScreen', '/Centre/iniciCentreScreen', Record<never, never>, Record<never, never>>,
    '/professor/iniciprofessor': RouteRecordInfo<'/professor/iniciprofessor', '/professor/iniciprofessor', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin/indexadmin.vue': {
      routes: '/admin/indexadmin'
      views: never
    }
    'src/pages/admin/loginadmin.vue': {
      routes: '/admin/loginadmin'
      views: never
    }
    'src/pages/Centre/estatassignacions.vue': {
      routes: '/Centre/estatassignacions'
      views: never
    }
    'src/pages/Centre/estatpeticionsscreen.vue': {
      routes: '/Centre/estatpeticionsscreen'
      views: never
    }
    'src/pages/Centre/formularialumnes.vue': {
      routes: '/Centre/formularialumnes'
      views: never
    }
    'src/pages/Centre/iniciCentreScreen.vue': {
      routes: '/Centre/iniciCentreScreen'
      views: never
    }
    'src/pages/professor/iniciprofessor.vue': {
      routes: '/professor/iniciprofessor'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
