/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account': RouteRecordInfo<'/account', '/account', Record<never, never>, Record<never, never>>,
    '/admin/convidaradmin': RouteRecordInfo<'/admin/convidaradmin', '/admin/convidaradmin', Record<never, never>, Record<never, never>>,
    '/admin/fasesadmin': RouteRecordInfo<'/admin/fasesadmin', '/admin/fasesadmin', Record<never, never>, Record<never, never>>,
    '/admin/gestiorepresentants': RouteRecordInfo<'/admin/gestiorepresentants', '/admin/gestiorepresentants', Record<never, never>, Record<never, never>>,
    '/admin/indexadmin': RouteRecordInfo<'/admin/indexadmin', '/admin/indexadmin', Record<never, never>, Record<never, never>>,
    '/admin/informesadmin': RouteRecordInfo<'/admin/informesadmin', '/admin/informesadmin', Record<never, never>, Record<never, never>>,
    '/admin/peticionsadmin': RouteRecordInfo<'/admin/peticionsadmin', '/admin/peticionsadmin', Record<never, never>, Record<never, never>>,
    '/admin/tallersadmin': RouteRecordInfo<'/admin/tallersadmin', '/admin/tallersadmin', Record<never, never>, Record<never, never>>,
    '/admin/usuaris': RouteRecordInfo<'/admin/usuaris', '/admin/usuaris', Record<never, never>, Record<never, never>>,
    '/centre/assignacions': RouteRecordInfo<'/centre/assignacions', '/centre/assignacions', Record<never, never>, Record<never, never>>,
    '/centre/estatpeticions': RouteRecordInfo<'/centre/estatpeticions', '/centre/estatpeticions', Record<never, never>, Record<never, never>>,
    '/centre/formulariCentre': RouteRecordInfo<'/centre/formulariCentre', '/centre/formulariCentre', Record<never, never>, Record<never, never>>,
    '/centre/indexcentre': RouteRecordInfo<'/centre/indexcentre', '/centre/indexcentre', Record<never, never>, Record<never, never>>,
    '/confirmar-participacion': RouteRecordInfo<'/confirmar-participacion', '/confirmar-participacion', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/professor/detallsprofessor': RouteRecordInfo<'/professor/detallsprofessor', '/professor/detallsprofessor', Record<never, never>, Record<never, never>>,
    '/professor/iniciprofessor': RouteRecordInfo<'/professor/iniciprofessor', '/professor/iniciprofessor', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/account.vue': {
      routes: '/account'
      views: never
    }
    'src/pages/admin/convidaradmin.vue': {
      routes: '/admin/convidaradmin'
      views: never
    }
    'src/pages/admin/fasesadmin.vue': {
      routes: '/admin/fasesadmin'
      views: never
    }
    'src/pages/admin/gestiorepresentants.vue': {
      routes: '/admin/gestiorepresentants'
      views: never
    }
    'src/pages/admin/indexadmin.vue': {
      routes: '/admin/indexadmin'
      views: never
    }
    'src/pages/admin/informesadmin.vue': {
      routes: '/admin/informesadmin'
      views: never
    }
    'src/pages/admin/peticionsadmin.vue': {
      routes: '/admin/peticionsadmin'
      views: never
    }
    'src/pages/admin/tallersadmin.vue': {
      routes: '/admin/tallersadmin'
      views: never
    }
    'src/pages/admin/usuaris.vue': {
      routes: '/admin/usuaris'
      views: never
    }
    'src/pages/centre/assignacions.vue': {
      routes: '/centre/assignacions'
      views: never
    }
    'src/pages/centre/estatpeticions.vue': {
      routes: '/centre/estatpeticions'
      views: never
    }
    'src/pages/centre/formulariCentre.vue': {
      routes: '/centre/formulariCentre'
      views: never
    }
    'src/pages/centre/indexcentre.vue': {
      routes: '/centre/indexcentre'
      views: never
    }
    'src/pages/confirmar-participacion.vue': {
      routes: '/confirmar-participacion'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/professor/detallsprofessor.vue': {
      routes: '/professor/detallsprofessor'
      views: never
    }
    'src/pages/professor/iniciprofessor.vue': {
      routes: '/professor/iniciprofessor'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
